### ISSUE TITLE
Delete launcher-root-partial.html

### ISSUE THREAD

**Issue by warpech** [Polyjuice/launcher-include#1]
It seems that the previous file `launcher-root-partial.html` was added to this repo by accident

**Comment by tomalec** [comment]
not by accident, but to keep backward compatibility, until all apps are migrated.

**Comment by warpech** [comment]
Good point. Search shows that few more apps need to be changed: https://github.com/search?q=launcher-root-partial&type=Code&utf8=%E2%9C%93

There is one external app: https://github.com/Ripipip/adfenix-backend. It is running a customised Launcher, so it will not be immediately affected.

**Comment by miyconst** [comment]
`launcher-root-partial` still left in:

- [ ] https://github.com/Polyjuice/microLauncher
- [ ] https://github.com/Polyjuice/AppStoreClient
- [ ] https://github.com/Polyjuice/Launcher

AppStoreClient is an app of @andwah, but I can replace `launcher-root-partial` with `polyjuice-include` as well.

**Comment by tomalec** [comment]
Launcher was already updated with launcher-partial release

**Comment by miyconst** [comment]
`launcher-root-partial.html` is already removed.
