### ISSUE TITLE
Invalid test suite

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/launcher-include#3]
It looks like the tests for `launcher-include` were copied from `starcounter-include` and do not work with `launcher-include/starcounter-include.html`. This should be fixed.

cc @tomalec.

**Comment by warpech** [comment]
Shouldn't Launcher's include test suite pass `starcounter-include` tests?

**Comment by miyconst** [comment]
Some of them should, but not all of them.

For example this test.
https://github.com/Polyjuice/launcher-include/blob/gh-pages/tests/partialAttribute/not_provided.html#L26
Will never pass as first child of launcher-include is not a `<template is="imported-template">`.

**Comment by tomalec** [comment]
Test suite is now profiled for Launcher include, and all tests passes.
I created another issue related to DRYing it. https://github.com/Polyjuice/launcher-include/issues/4
